---
title: "GP2"
author: 
date: "3/17/2021"
output: html_document
---
## Importing and Cleaning Data

```{r}
library(tidyverse, warn.conflicts = FALSE)
library(lubridate, warn.conflicts = FALSE)

loans <- read.csv('loans.csv', stringsAsFactors = TRUE)

#Factorizing variables
loans$loan_status_description <- as.factor(loans$loan_status_description)
loans$prosper_rating <- as.factor(loans$prosper_rating)
loans$listing_category_id <- as.factor(loans$listing_category_id)
loans$income_range_description <- as.factor(loans$income_range_description)
loans$employment_status_description <- as.factor(loans$employment_status_description)
loans$occupation <- as.factor(loans$occupation)
loans$borrower_state <- as.factor(loans$borrower_state)
loans$borrower_city <- as.factor(loans$borrower_city)
loans$scorex <- as.factor(loans$scorex)

#Converting logical variables into factors
loans$income_verifiable <- as.factor(ifelse(loans$income_verifiable == TRUE, 1, 0))
loans$is_homeowner <- as.factor(ifelse(loans$is_homeowner == TRUE, 1, 0))

#Dropping redundant columns
loans$loan_status <- NULL
loans$income_range <- NULL
  
#Creating new columns
loans$loan_origination_month <- as.factor(month(strptime(loans$loan_origination_date, format='%m/%d/%Y')))
loans$first_recorded_credit_line_year <- year(strptime(loans$first_recorded_credit_line, format='%m/%d/%Y'))

loans$loan_origination_date <- NULL
loans$first_recorded_credit_line <- NULL
loans$borrower_city <- NULL
loans$borrower_state <- NULL

loans$number_of_days <- NULL
loans$principal_balance <- NULL
loans$loan_status_description <- NULL
loans$listing_monthly_payment <- NULL

loans <- na.omit(loans)
```

## Linear Regression Model
```{r}
linearmodel <- step(lm(formula = borrower_rate ~., data=loans))

summary(linearmodel)

lm2 <- lm(formula = borrower_rate ~ amount_funded + prosper_rating + 
    listing_term + scorex + prosper_score + listing_category_id + 
    income_range_description + stated_monthly_income + income_verifiable + 
    dti_wprosper_loan + employment_status_description + lender_indicator + 
    monthly_debt + current_delinquencies + public_records_last10_years + 
    credit_lines_last7_years + current_credit_lines + open_credit_lines + 
    bankcard_utilization + total_open_revolving_accounts + real_estate_balance + 
    revolving_balance + total_inquiries + was_delinquent_derog + 
    is_homeowner + loan_origination_month, data = loans)

summary(lm2)

```

## Logistic Regression Model
```{r}
loans$defaulted <- ifelse(loans$loan_status_description == 'DEFAULTED' | loans$loan_status_description == 'CHARGEOFF', 1, 0)
logisticmodel <- glm(formula = defaulted ~ ., data=loans, family = 'binomial')
summary(logisticmodel)
```

